version: '3.8'

services:

  app:
    build: .
    container_name: bankcards-app
    ports:
      - "9010:9010"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydb
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - db


  db:
    image: postgres:13
    container_name: bankcards-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: